path:
  train_path: ../dataset/train/train.csv
  dev_path: ../dataset/dev/dev.csv
  test_path: ../dataset/test/test.csv
  save_path: save_models/

data:
  shuffle: True
  train_ratio: 0.8

model:
  model_name: klue/roberta-small

train:
  max_epoch: 2
  batch_size: 32
  learning_rate: 1
  loss: nll
  dropout: 0.1
  logging_steps: 5
  
utils:
  seed: 42
  monitor: val_pearson
  patience: 20
  top_k: 3

k_fold:
  use_k_fold: False
  num_folds: 5
  num_split: 5