path:
  train_path: ./dataset/train/train.csv
  dev_path: ./dataset/dev/dev.csv
  test_path: ./dataset/test/test.csv
  predict_path: ./dataset/predict/predict.csv
  # inference를 하는 경우 로드할 모델의 경로를 입력해주세요.
  load_model_path: /opt/ml/level2_klue_nlp-level2-nlp-05/step_saved_model/klue-roberta-small/18-14-42/checkpoint-500/pytorch_model.bin

model:
  exp_name: CustomRBERT #model.py에서 사용할 모델 이름
  model_name: klue/roberta-small

data:
  tem: True #typed entity token 사용시 True

train:
  max_epoch: 1
  batch_size: 32
  learning_rate: 3e-5
  loss: focal # loss.py 맨 아래 config 되어 있는 값을 받아서 loss 함수를 가져옵니다.
  save_steps: 500
  # eval_steps은 반드시 save_steps의 배수여야 합니다!!!! """save_steps = n * eval_steps"""
  eval_steps: 500
  logging_steps: 500
  
utils:
  seed: 42
  monitor: micro f1 score
  patience: 20
  top_k: 3